- name: Play Variables
  hosts: localhost
  vars:
    URL: play.variable.com
  tasks:
    - name: Print Play Variable
      ansible.builtin.debug:
        msg: URL={{URL}}

- name: Play Variables from Files
  hosts: localhost
  vars_files:
    - var.yml
  tasks:
    - name: Print Play Variable from Files
      ansible.builtin.debug:
        msg: URL={{URL}}