- name: Play Variables
  hosts: localhost
  vars:
    URL: play.variable.com
  tasks:
    - name: Print Play Variable
      ansible.builtin.debug:
        msg: URL={{URL}}

- name: Play Variables from Files
  hosts: localhost
  # Vars_files works only on the play level
  vars_files:
    - var.yml
  tasks:
    - name: Print Play Variable from Files
      ansible.builtin.debug:
        msg: URL={{URL}}

- name: Task Level Variables
  hosts: localhost
  tasks:
    - name: Print Play Variable from Files
      vars: ## These vars are only for this task, next task on the same play cannot access it
        URL: task.example.com
      ansible.builtin.debug:
        msg: URL={{URL}}

- name: Vars from Inventory
  hosts: all
  tasks:
    - name: Print Play Variable from Inventory
      ansible.builtin.debug:
        msg: "URL={{URL}}, Hostname of server = {{ansible_hostname}}"

- name: Register a variable
  hosts: localhost
  tasks:
    - name: Get Uptime Output
      ansible.builtin.shell: uptime
      register: out

    - name: Print out
      ansible.builtin.debug:
      msg: "{{ out }}"
